### ISSUE TITLE
Peer Dependency Breaks Build Configuration

### ISSUE THREAD

**Issue by HiptJo** [HiptJo/active-connect#97]
**Describe the bug**
When running an application build, it crashes due to the following error:

```
node_modules/@types/ws/index.d.ts:328:34 - error TS2315: Type 'Server' is not generic.

328         server?: HTTPServer<V> | HTTPSServer<V> | undefined;
```

This is caused by an misbehaviour within `@types/ts@8.5.5` and works with version `8.5.4`.
